### ISSUE TITLE
Fwd Bulk statistics

### ISSUE THREAD

**Issue by kunavarion** [GintsEngelen/WTMC2021-Code#1] opened 2021-10-22 00:25 UTC
Hello,

The following statistics seem to be all 0:

Fwd Bytes/Bulk Avg
Fwd Packet/Bulk Avg
Fwd Bulk Rate Avg

which seems strange if the traffic is entirely representative. Is this an additional bug? or is it such that these features are entirely irrelevant

**Comment by GintsEngelen** [comment] 2021-10-22 17:16
Hello, 

Thank you for pointing out this issue. Lisa has been very quick to provide a fix, and I have confirmed that the tool now correctly calculates the Fwd Bulk statistics as well as the Bwd Bulk statistics, which also had an issue (as pointed out by Lisa). Her fix has been merged into the main repo of our forked [CICFlowMeter repo](https://github.com/GintsEngelen/CICFlowMeter).

As an extra sanity check, could you help me confirm that the issue is now resolved?

**Comment by kunavarion** [comment] 2021-10-23 03:19
Hello,

Sorry, I actually raised the issue with a personal/private Github account (I am Lisa :) ). I greatly appreciate the csv files being re-uploaded (I’m a PhD student working with limited computational and networking resources from home)

I’ll raise any further issues I come across as I comb through my experiment results

Best regards,
Lisa

**Closed as completed** 2021-10-23 07:35 UTC
